. ~/.bashrc

export PATH="$HOME/.cargo/bin:$PATH"

export PATH="$HOME/.poetry/bin:$PATH"
if [ -e /Users/berekuk/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/berekuk/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
