set runtimepath^=~/etc/vim
set nocompatible      " nobody cares about stupid classic vi
filetype off

source ~/etc/vim/plugins.vim

filetype plugin indent on

set ttyfast

set modelines=5

set encoding=utf8     " utf is default
set fileencodings=utf-8,cp1251 " detect cp1251 if possible

" Spaces instead of tabs.
set expandtab

set tabstop=8
set shiftwidth=4
set softtabstop=4

set backspace=indent,eol,start " allow backspace everywhere

" Highlight trailing tabs and spaces.
set list
set listchars=tab:↣⇢,trail:·

set scrolloff=3         " going to try it for some time and see if I like it

set hlsearch            " highlight all search results
set incsearch           " incremental search

set gdefault    " s///g by default

set ruler                   " useful info at the bottom of the screen
set laststatus=2            " even if only one file is open

""" I'd like to use this feature, but many people don't comply to 80-columns
""" limit, and it gets too annoying
"if exists('+colorcolumn')
"  set colorcolumn=80 " long lines are evil
"else
"  au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
"endif

set history=50         " increase command history buffer
set showcmd

set wrap

" set autoindent           " keep cursor in the same column on cr
" Smart indentation of { and }.
" set smartindent <--- why is this commented? arrgh, my indentation settings are messed up.
" ...but disable indentation of comments.
inoremap # X#

set visualbell          " don't beep!
set wildmenu            " improved file select menu
set wildmode=list:longest " consistent with bash

set background=dark
colorscheme base16-default-dark

set directory=~/tmp/vim//

" gx opens urls with '?', '&' and ':'.
set isfname+=?,&,:

syntax on

source ~/etc/vim/bindings.vim

source ~/etc/vim/gitcommit.vim
source ~/etc/vim/markdown.vim
source ~/etc/vim/make.vim
source ~/etc/vim/perl.vim
source ~/etc/vim/ruby.vim
source ~/etc/vim/js.vim
source ~/etc/vim/html.vim
source ~/etc/vim/yaml.vim


""" useful for syntax debugging
"function! SyntaxItem()
"    return synIDattr(synID(line("."),col("."),1),"name")
"endfunction
"set statusline+=%{SyntaxItem()}

""""""""""""""""" TODO """""""""""""""""
" set hidden?
