filetype off
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()

set runtimepath^=~/etc/vim
set nocompatible      " отключаем совместимость с классическим vi

set autoindent           " автоотступы, перенос строки оставляет курсор в той же колонке
set encoding=utf8     " дефолтная кодировка
set fileencodings=utf-8,cp1251 " автоопределение кодировки
set tabstop=4            " ширина табов 4
set shiftwidth=4         " ...никогда не разбирался, в чем разница
set softtabstop=4      " ...между этими тремя опциями
set modeline             " включаем modeline - возможность в текстовом файле указать опции vim
set modelines=5       " modeline работает в верхних и нижних 5 строчках
set expandtab           " пробелы вместо табов
set listchars=tab:↣⇢,trail:· " подсветка табов и пробелов в конце строки
set list                       " включена по дефолту, как рекомендует наша wiki; жаль, что не все аккуратно к этому относятся
au FileType make setlocal noexpandtab " не заменять табы пробелами в Makefile'ах

set hlsearch             " по дефолту результаты поиска подсвечиваются
set incsearch           " инкрементальный поиск - курсор перемещается в процессе набора искомой строки
set ruler                   " включаем полезную информацию в предпоследней строке экрана
set laststatus=2       " всегда, даже если открыт только один файл
set history=50         " увеличиваем буфер команд
set showcmd           " показывать всякую дополнительную информацию в процессе набора команды

set background=light
colorscheme my

" отключить подсветку результатов предыдущего поиска
map <F2> :nohlsearch<CR>

" включить/выключить отображение табов
map <F3> :set list!<CR>

" переключение кодировок текущего файла
map <F5> :e ++enc=cp1251<CR>
map <F6> :e ++enc=utf-8<CR>
map <F7> :e ++enc=koi8-r<CR>

" включить/выключить set paste (отключение автоотступов, нужно при копипасте откуда-нибудь из браузера)
set pastetoggle=<F8>

" удалить все пробелы на конце строк
nnoremap <LocalLeader><Space> :%s/\s\+$//<CR>

autocmd BufNewFile,BufRead COMMIT_EDITMSG set filetype=gitcommit " правильная подсветка при редактировании коммита после git commit

filetype plugin on " включаем опознавание типов файлов
syntax on " и подсветку синтаксиса

" автозамена title окна в screen'е на имя текущего файла
" не успел еще понять, полезно это или вредно (оно не заменяется обратно после выхода из vim'а)
if $TERM=='screen'
   exe "set title titlestring=vim:%f"
   exe "set title t_ts=\<ESC>k t_fs=\<ESC>\\"
endif
