#!/usr/bin/env perl

use strict;
use warnings;

use IPC::System::Simple;
use autodie qw(:all);

sub main {
    die "Usage: distribute HOSTNAME" unless @ARGV == 1;
    my $host = shift @ARGV;

    system("ssh $host 'mkdir -p ~/bin'");
    system("scp ~/etc/script/accept_configs $host:~/bin/");
    system("(cd ~/etc && git archive --format=tar HEAD) | ssh $host '~/bin/accept_configs'");
}

main unless caller;
