#!/bin/sh

set -e
cd
echo 'Linking dotfiles'
SOURCE=etc/dotfiles

for file in `cd $SOURCE && find . -type f | perl -pnE 's{\./}{}'`; do
    dst=".$file"

    # 'etc/dotfiles' + '.config/karabiner/karabiner.json' -> '../../etc/dotfiles'
    src_dir=$(python -c "import os.path; import sys; print(os.path.relpath(sys.argv[1], os.path.dirname(sys.argv[2])))" $SOURCE $dst)

    src="$src_dir/$file"

    dst_dir=`dirname $dst`
    if [ -n "$dst_dir" ]; then
        mkdir -p $dst_dir
    fi

    rm -f $dst
    ln -s $src $dst
done

VUNDLE_DIR=~/etc/vim/bundle/Vundle.vim
if ! [ -d $VUNDLE_DIR ]; then
    git clone https://github.com/gmarik/vundle.git $VUNDLE_DIR
fi

mkdir -p ~/tmp/vim

echo 'Installing vim bundles'
$(which vim) -N -u ~/etc/vim/plugins.vim +PluginInstall +qall >/dev/null 2>/dev/null
