#!/bin/sh

set -e
cd
echo 'Linking dotfiles'
SOURCE=etc/dotfiles
for file in `cd $SOURCE && find . -type f | perl -pnE 's{\./}{}'`; do
    src="$SOURCE/$file"
    dst=".$file"

    dst_dir=`dirname $dst`
    if [ -n "$dst_dir" ]; then
        mkdir -p $dst_dir
    fi

    rm -f $dst
    ln -s $src $dst
done

VUNDLE_DIR=~/etc/vim/bundle/Vundle.vim
if ! [ -d $VUNDLE_DIR ]; then
    git clone https://github.com/gmarik/vundle.git $VUNDLE_DIR
fi

mkdir -p ~/tmp/vim

echo 'Installing vim bundles'
$(which vim) -N -u ~/etc/vim/plugins.vim +PluginInstall +qall >/dev/null 2>/dev/null
